---
title: "A2_code"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# packages
library(pacman)
p_load(tidyverse, ggunchained, rstan, rethinking)


# STAN SETUP
options(mc.cores = parallel::detectCores())

M <- file.path(Sys.getenv("HOME"), ".R", ifelse(.Platform$OS.type == "windows", "Makevars.win", "Makevars"))
file.edit(M)

rstan_options(auto_write = TRUE)
```


# QUESTION 1

```{r}
ric <- data.frame(ID = rep("Riccardo", 6),
                      answer = c(0, 0, 0, 1, 1, 1))

kri <- data.frame(ID = rep("Kristian", 4),
                  answer = c(0, 0, 1, 1))

jos <- data.frame(ID = rep("Josh", 198),
                  answer = c(rep(1, 160), rep(0, 38)))

mik <- data.frame(ID = rep("Mikkel", 132),
                  answer = c(rep(1, 66), rep(0, 66)))

q1_data <- full_join(ric, kri) %>%
  full_join(jos) %>%
  full_join(mik)
```


# QUESTION 2
```{r}

```


# QUESTION 3
```{r}

```


# QUESTION 4
```{r}

```


# QUESTION 5
```{r}

```


# QUESTION 6
```{r}

```


# QUESTION 7 - bonus
```{r}

```
